"""empty message

Revision ID: 0b8ac9fbf4b0
Revises: 4e4f049e7ff9
Create Date: 2021-10-12 13:41:39.176644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b8ac9fbf4b0'
down_revision = '4e4f049e7ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_corevariable', sa.String(length=30), nullable=True),
    sa.Column('abbreviation_corevariable', sa.String(length=4), nullable=True),
    sa.Column('description_corevariable', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_moderator', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('utau_tmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_utautmodel', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utau_tmodel_name_utautmodel'), 'utau_tmodel', ['name_utautmodel'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_study', sa.String(length=64), nullable=True),
    sa.Column('description_study', sa.String(length=300), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_underway', sa.Boolean(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['utau_tmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utautmodel_corevariable',
    sa.Column('utau_tmodel_id', sa.Integer(), nullable=True),
    sa.Column('core_variable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['core_variable_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['utau_tmodel_id'], ['utau_tmodel.id'], )
    )
    op.create_table('questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_questionnaire', sa.String(length=64), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_question', sa.String(length=100), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('study_user')
    op.drop_table('questionnaire')
    op.drop_table('utautmodel_corevariable')
    op.drop_table('study')
    op.drop_table('followers')
    op.drop_index(op.f('ix_utau_tmodel_name_utautmodel'), table_name='utau_tmodel')
    op.drop_table('utau_tmodel')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('moderator')
    op.drop_table('core_variable')
    # ### end Alembic commands ###
