"""empty message

Revision ID: 0c8029f44c85
Revises: 7ce55b4a4497
Create Date: 2021-10-21 10:16:20.192744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8029f44c85'
down_revision = '7ce55b4a4497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_question', sa.String(length=100), nullable=True),
    sa.Column('corevariable_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corevariable_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_question', sa.String(length=100), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('corevariable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corevariable_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question')
    op.drop_table('answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.SMALLINT(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_question', sa.VARCHAR(length=100), nullable=True),
    sa.Column('questionnaire_id', sa.INTEGER(), nullable=True),
    sa.Column('corevariable_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['corevariable_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questionnaire_question')
    op.drop_table('standard_question')
    # ### end Alembic commands ###
