"""empty message

Revision ID: 11709beda1ee
Revises: 11dc6b8fce56
Create Date: 2021-10-12 11:29:56.202640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11709beda1ee'
down_revision = '11dc6b8fce56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'study', 'utau_tmodel', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study', type_='foreignkey')
    # ### end Alembic commands ###
