"""empty message

Revision ID: 2207180728cc
Revises: 46c377046a20
Create Date: 2021-11-09 12:56:56.996183

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2207180728cc'
down_revision = '46c377046a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_demographic',
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('demographic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demographic_id'], ['demographic.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaire.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaire_demographic')
    # ### end Alembic commands ###
