"""empty message

Revision ID: 237bce31861c
Revises: 0b8ac9fbf4b0
Create Date: 2021-10-12 13:58:07.673762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237bce31861c'
down_revision = '0b8ac9fbf4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'core_variable', ['abbreviation_corevariable'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'core_variable', type_='unique')
    # ### end Alembic commands ###
