"""empty message

Revision ID: 26ad6c57ec46
Revises: 2207180728cc
Create Date: 2021-11-09 14:21:45.198042

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26ad6c57ec46'
down_revision = '2207180728cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demographic_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('demographic_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['demographic_id'], ['demographic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demographic_answer')
    # ### end Alembic commands ###
