"""empty message

Revision ID: 46c377046a20
Revises: e4b253faef4e
Create Date: 2021-11-09 12:02:08.755588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '46c377046a20'
down_revision = 'e4b253faef4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demographic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('questiontype_name', sa.String(), nullable=True),
    sa.Column('choices', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['questiontype_name'], ['question_type.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographic_name'), 'demographic', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demographic_name'), table_name='demographic')
    op.drop_table('demographic')
    # ### end Alembic commands ###
