"""empty message

Revision ID: 4e4f049e7ff9
Revises: e2c4888a3281
Create Date: 2021-10-12 13:38:48.212026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4f049e7ff9'
down_revision = 'e2c4888a3281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utautmodel_corevariable', sa.Column('utau_tmodel_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'utautmodel_corevariable', type_='foreignkey')
    op.create_foreign_key(None, 'utautmodel_corevariable', 'utau_tmodel', ['utau_tmodel_id'], ['id'])
    op.drop_column('utautmodel_corevariable', 'utau_tmodel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utautmodel_corevariable', sa.Column('utau_tmodel', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'utautmodel_corevariable', type_='foreignkey')
    op.create_foreign_key(None, 'utautmodel_corevariable', 'utau_tmodel', ['utau_tmodel'], ['id'])
    op.drop_column('utautmodel_corevariable', 'utau_tmodel_id')
    # ### end Alembic commands ###
