"""empty message

Revision ID: 553b6eb9dbfd
Revises: b21dc7e27e5d
Create Date: 2021-11-01 15:37:17.385509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553b6eb9dbfd'
down_revision = 'b21dc7e27e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
