"""empty message

Revision ID: 57b5c3a6f2f5
Revises: e623811a2929
Create Date: 2021-10-15 10:20:23.749949

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '57b5c3a6f2f5'
down_revision = 'e623811a2929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_study_name_study'), 'study', ['name_study'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_name_study'), table_name='study')
    # ### end Alembic commands ###
