"""empty message

Revision ID: 6815a9f70381
Revises: 4007789594a0
Create Date: 2021-10-12 14:22:11.756946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6815a9f70381'
down_revision = '4007789594a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('influenced_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['influenced_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['utau_tmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    # ### end Alembic commands ###
