"""corevariables

Revision ID: 6a71b0c89139
Revises: cc96698ca81c
Create Date: 2021-10-12 10:45:55.984593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71b0c89139'
down_revision = 'cc96698ca81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_variable', sa.Column('description_corevariable', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_variable', 'description_corevariable')
    # ### end Alembic commands ###
