"""empty message

Revision ID: 6b24a9ae45aa
Revises: 26ad6c57ec46
Create Date: 2021-11-09 14:22:35.329054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b24a9ae45aa'
down_revision = '26ad6c57ec46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_age', table_name='case')
    op.drop_column('case', 'sex')
    op.drop_column('case', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('case', sa.Column('sex', sa.VARCHAR(), nullable=True))
    op.create_index('ix_case_age', 'case', ['age'], unique=False)
    # ### end Alembic commands ###
