"""empty message

Revision ID: 71dee79af1b2
Revises: a351345f0d88
Create Date: 2021-11-01 13:28:39.565835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dee79af1b2'
down_revision = 'a351345f0d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('questiongroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'question_group', ['questiongroup_id'], ['id'])
    op.add_column('question_group', sa.Column('questionnaire_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question_group', 'questionnaire', ['questionnaire_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_group', type_='foreignkey')
    op.drop_column('question_group', 'questionnaire_id')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'questiongroup_id')
    # ### end Alembic commands ###
