"""empty message

Revision ID: 78fac972dc85
Revises: 8d7c5274f2b1
Create Date: 2021-11-05 13:42:48.163706

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '78fac972dc85'
down_revision = '8d7c5274f2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'case', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'case_id')
    # ### end Alembic commands ###
