"""corevariables

Revision ID: 7d3f9d2f54a0
Revises: 6aee31a1d9c0
Create Date: 2021-10-12 10:37:18.485203

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d3f9d2f54a0'
down_revision = '6aee31a1d9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_variable', sa.Column('abbreviation_corevariable', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_variable', 'abbreviation_corevariable')
    # ### end Alembic commands ###
