"""empty message

Revision ID: 8e681e36a2d7
Revises: f8529694ee34
Create Date: 2021-10-29 10:29:53.750310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e681e36a2d7'
down_revision = 'f8529694ee34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_visitor', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_visitor')
    )
    op.add_column('questionnaire', sa.Column('code_questionnaire', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire', 'code_questionnaire')
    op.drop_table('visitor')
    # ### end Alembic commands ###
