"""studies

Revision ID: 941afa71cf74
Revises: bb971b5db4ce
Create Date: 2021-10-07 17:43:47.688210

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '941afa71cf74'
down_revision = 'bb971b5db4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study', 'name_study',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study', 'name_study',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
