"""empty message

Revision ID: 96e443b7df2a
Revises: dc6367bc4959
Create Date: 2021-11-02 14:46:43.395451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e443b7df2a'
down_revision = 'dc6367bc4959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'case', ['session_id'])
    op.create_foreign_key(None, 'case', 'questionnaire', ['questionnaire_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_constraint(None, 'case', type_='unique')
    # ### end Alembic commands ###
