"""utautmodel

Revision ID: a464eef88d7c
Revises: 6a71b0c89139
Create Date: 2021-10-12 11:15:32.663109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a464eef88d7c'
down_revision = '6a71b0c89139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utautmodel_corevariable',
    sa.Column('utau_tmodel', sa.Integer(), nullable=True),
    sa.Column('core_variable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['core_variable_id'], ['core_variable.id'], ),
    sa.ForeignKeyConstraint(['utau_tmodel'], ['utau_tmodel.id'], )
    )
    op.add_column('study', sa.Column('linked_model', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study', 'utau_tmodel', ['linked_model'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.drop_column('study', 'linked_model')
    op.drop_table('utautmodel_corevariable')
    # ### end Alembic commands ###
