"""empty message

Revision ID: a967fa09a20a
Revises: 6b24a9ae45aa
Create Date: 2021-11-09 15:17:55.816267

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a967fa09a20a'
down_revision = '6b24a9ae45aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographic', sa.Column('optional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographic', 'optional')
    # ### end Alembic commands ###
