"""empty message

Revision ID: b53a596903d1
Revises: bbeef92dfcb9
Create Date: 2021-10-20 15:05:43.376177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53a596903d1'
down_revision = 'bbeef92dfcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'])
    op.drop_index('ix_utau_tmodel_name_utautmodel', table_name='utau_tmodel')
    op.create_index(op.f('ix_utau_tmodel_name_utautmodel'), 'utau_tmodel', ['name_utautmodel'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utau_tmodel_name_utautmodel'), table_name='utau_tmodel')
    op.create_index('ix_utau_tmodel_name_utautmodel', 'utau_tmodel', ['name_utautmodel'], unique=False)
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
