"""empty message

Revision ID: bbeef92dfcb9
Revises: 15c79f8bc176
Create Date: 2021-10-20 15:04:31.452554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeef92dfcb9'
down_revision = '15c79f8bc176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'])
    op.drop_index('ix_utau_tmodel_name_utautmodel', table_name='utau_tmodel')
    op.create_index(op.f('ix_utau_tmodel_name_utautmodel'), 'utau_tmodel', ['name_utautmodel'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utau_tmodel_name_utautmodel'), table_name='utau_tmodel')
    op.create_index('ix_utau_tmodel_name_utautmodel', 'utau_tmodel', ['name_utautmodel'], unique=False)
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###
