"""empty message

Revision ID: ca20460f78c0
Revises: fc29a4d73520
Create Date: 2021-11-10 13:06:16.811011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca20460f78c0'
down_revision = 'fc29a4d73520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire', sa.Column('scale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire', 'scale')
    # ### end Alembic commands ###
