"""empty message

Revision ID: e2c4888a3281
Revises: c6ac14228acd
Create Date: 2021-10-12 13:23:04.773328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c4888a3281'
down_revision = 'c6ac14228acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utau_tmodel_name_utautmodel', table_name='utau_tmodel')
    op.create_index(op.f('ix_utau_tmodel_name_utautmodel'), 'utau_tmodel', ['name_utautmodel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utau_tmodel_name_utautmodel'), table_name='utau_tmodel')
    op.create_index('ix_utau_tmodel_name_utautmodel', 'utau_tmodel', ['name_utautmodel'], unique=False)
    # ### end Alembic commands ###
