"""empty message

Revision ID: e4b253faef4e
Revises: 9a1361039506
Create Date: 2021-11-08 11:38:02.213451

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e4b253faef4e'
down_revision = '9a1361039506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'completed_cases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('completed_cases', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
