"""empty message

Revision ID: f8529694ee34
Revises: 0c8029f44c85
Create Date: 2021-10-21 10:17:02.276023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8529694ee34'
down_revision = '0c8029f44c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('questionnairequestion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionnairequestion_id'], ['questionnaire_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
