"""empty message

Revision ID: fc29a4d73520
Revises: a967fa09a20a
Create Date: 2021-11-10 11:06:37.878635

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc29a4d73520'
down_revision = 'a967fa09a20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utau_tmodel_name', table_name='utau_tmodel')
    op.create_index(op.f('ix_utau_tmodel_name'), 'utau_tmodel', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utau_tmodel_name'), table_name='utau_tmodel')
    op.create_index('ix_utau_tmodel_name', 'utau_tmodel', ['name'], unique=False)
    # ### end Alembic commands ###
